security:
    providers:
      webservice:
        id: App\Security\Authentication\UserProvider

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: ~
            simple_form:
              authenticator: App\Security\Authentication\SafeAuthenticator
              login_path: login
              check_path: login
              success_handler: App\Security\Authentication\AuthenticationSuccessHandler
              failure_handler: App\Security\Authentication\AuthenticationFailureHandler
            logout:
               path: logout
               target: /

    access_control:
         - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
         - { path: ^/first_login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
         - { path: ^/, roles: ROLE_USER }
