image: node:10.5.0-alpine

before_script: 
  - echo '@php http://nl.alpinelinux.org/alpine/v3.8/community' >> /etc/apk/repositories
  - apk update
  - apk add wget curl git php7@php php7-curl@php php7-openssl@php php7-json@php php7-phar@php php7-dom@php
  - apk add php7-mbstring@php php7-iconv@php php7-pdo@php php7-pdo_mysql@php php7-xml@php php7-ctype@php php7-simplexml@php php7-tokenizer@php
  - apk add python2 make g++ openssh-client sshpass
  - apk add coreutils # contains better date
  - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/bin --filename=composer

release_job:
    only:
      - master
    script:
      - composer install
      - npm install
      - npm run build

      - mv .env.dist .env
      - sed -i -e "s/APP_ENV=.*/APP_ENV=prod/g" .env
      - sed -i -e "s/APP_SECRET=.*/APP_SECRET=${APP_SECRET}/g" .env
      - sed -i -e "s#DATABASE_URL=.*#DATABASE_URL=${DATABASE_URL}#g" .env
      - php bin/console doctrine:migrations:migrate --no-interaction

      - NEW_UUID=$(date +%y%m%d%H%M%S)
      - echo -e "-rename app old_${NEW_UUID}\nmkdir app" > /tmp/sftp
      - sshpass -p "${PASSWORD}" sftp -oBatchMode=no -o "StrictHostKeyChecking no" -P 2222 -b /tmp/sftp ${USER}@florianbackmeier.de
      - sshpass -p "${PASSWORD}" scp -P 2222 -r . ${USER}@florianbackmeier.de:/app/
